site.title: Ren's PPE Notes
page.title: Home
site.description: Notes and completed exercises by Ren Phua (2023) for the BA in Philosophy, Politics, and Economics (PPE) at the University of Oxford.
# google_site_verification: 